Update ci-on-pull_req.yml

diff --git a/.github/workflows/ci-on-pull_req.yml b/.github/workflows/ci-on-pull_req.yml
--- a/.github/workflows/ci-on-pull_req.yml
+++ b/.github/workflows/ci-on-pull_req.yml
@@ -37,17 +37,30 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v3
 
-    - name: Prepare
-      run: mkdir -p output/$RELEASE/$ARCH
-
-    # Caching Docker images is not ready yet, see 
-    # https://github.com/storeman-developers/harbour-storeman-installer/blob/devel/cache-docker-images_github-ci.md
-    #- name: Cache Docker images of the Sailfish-SDK
-    #  id: cache-sdk
-    #  uses: actions/cache@v3
-    #  with:
-    #    path: $GITHUB_WORKSPACE/…
-    #    key: cache
+    - name: Prepare Podman to run rootless with a larger subuid / subgid range
+      run: |
+        # Required to increase insufficient sub[ug]id ranges for starting podman rootlessly:
+        subXid_range=100000
+        subXid_altered=false
+        me="$(whoami)"
+        subuid_me="$(grep "^$me:" /etc/subuid)"
+        subgid_me="$(grep "^$me:" /etc/subgid)"
+        if [ $(echo -n "$subuid_me" | grep -c '.*') -ne 1 ] || [ $(echo -n "$subgid_me" | grep -c '.*') -ne 1 ]; then
+          echo "Error: Multiple subuid or subgid ranges defined for $me"
+          exit 1
+        fi
+        if [ -n "$subXid_range" ] && [ "$subXid_range" -gt $(echo $subuid_me | cut -d : -f 3) ]; then
+          sudo sed -i "s/^$subuid_me\$/$me:$(echo $subuid_me | cut -d : -f 2):$subXid_range/" /etc/subuid
+          subXid_altered=true
+        fi
+        if [ -n "$subXid_range" ] && [ "$subXid_range" -gt $(echo $subgid_me | cut -d : -f 3) ]; then
+          sudo sed -i "s/^$subgid_me\$/$me:$(echo $subgid_me | cut -d : -f 2):$subXid_range/" /etc/subgid
+          subXid_altered=true
+        fi
+        # `podman system migrate` is neccesary when subuid or subgid ranges were altered, even if `podman` has not been started before.
+        if [ $subXid_altered = true ]; then
+          podman system migrate
+        fi
 
     - name: Restore cache
       uses: actions/cache/restore@v3
@@ -61,26 +74,8 @@ jobs:
 
     - name: Build ${{ env.ARCH }} on ${{ env.RELEASE }}
       run: |
-        # Required to increase insufficient sub[ug]id ranges:
-        subXid_range=100000
-        subXid_altered=false
-        me="$(whoami)"
-        subuid_me="$(grep "^$me:" /etc/subuid)"
-        subgid_me="$(grep "^$me:" /etc/subgid)"
-        if [ $(echo -n "$subuid_me" | grep -c '.*') -ne 1 ] || [ $(echo -n "$subgid_me" | grep -c '.*') -ne 1 ]
-        then exit 1
-        fi
-        if [ -n "$subXid_range" ] && [ "$subXid_range" -gt $(echo $subuid_me | cut -d : -f 3) ]
-        then sudo sed -i "s/^$subuid_me\$/$me:$(echo $subuid_me | cut -d : -f 2):$subXid_range/" /etc/subuid; subXid_altered=true
-        fi
-        if [ -n "$subXid_range" ] && [ "$subXid_range" -gt $(echo $subgid_me | cut -d : -f 3) ]
-        then sudo sed -i "s/^$subgid_me\$/$me:$(echo $subgid_me | cut -d : -f 2):$subXid_range/" /etc/subgid; subXid_altered=true
-        fi
-        if [ $subXid_altered = true ]
-        then podman system migrate
-        fi
         set -x
-        # `podman system migrate` is neccesary when subuid or subgid ranges were altered, even if `podman` has not been started before.
+        mkdir -p output/$RELEASE/$ARCH
         podman run --rm -v $PWD:/share docker.io/coderus/sailfishos-platform-sdk:$RELEASE /bin/sh -xc '
            mkdir -p build
            cd build
